baseURL = 'https://beellz.in'
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
title = " A Tech Enthusian"
author = "Beellz"
description = "Automatic Blogging from Github"
profilePicture = "images/profile_image.png"
mainSection = ["blog"]
